--- #crating multiple users
- hosts: all
  user: mastan
  sudo: yes
  connection: ssh
  gather_facts: yes
  tasks:
   - command: echo {{item}}
     with_items: [0, 2, 4, 6, 8, 10]
     when: item > 5
